### ISSUE TITLE
wiki: performance comparison on Summit

### ISSUE THREAD

**Issue by wkliao** [UO-OACISS/tau2#1]
Hi, @khuck 

In one of the prior RAPIDS monthly calls, you presented this [wiki page](https://github.com/UO-OACISS/tau2/wiki/Comparing-HDF5,-PnetCDF-and-BP4-with-ADIOS2-on-Summit) about performance comparison of ADIOS, HDF5, and PnetCDF. Thanks for the great work and I am happy to learn TAU being able to profile PnetCDF internal costs.

One question. The experiments shown in this wiki page uses PnetCDF version 1.8.1 which is quite old. Since its release in 1/28/2017, several optimizations have been added. The latest version is 1.12.0 just released in 9/30/2019. I can see the HDF5 experiment shown there uses version 1.10.5, the latest version of today. I am wondering if there is a reason not to use newer PnetCDF version. If you encountered building problems of new versions, please let me know and I can help to resolve.

cc @paralepsis  and @roblatham00

**Comment by khuck** [comment]
@wkliao - Thanks!  Yeah, 1.8.1 is the module installed on Titan.  Lipeng made the same comment, that his testing was with 1.12.0.  Because of that, I also tested with 1.12.0, however the results were the same.  So I just used the easier configuration to reproduce.

**Comment by wkliao** [comment]
@khuck 
Thanks. Could you point me to the benchmark program used in the evaluation?

**Comment by khuck** [comment]
```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h> /* strcpy(), strncpy() */
#include <unistd.h> /* getopt() */
#include <errno.h>

#include <mpi.h>
#include <pnetcdf.h>

#define NVARS 500

#define STEPS 100

#define ERR(e) {if((e)!=NC_NOERR){printf("Error at line=%d: %s\n", __LINE__, ncmpi_strerror(e));nerrs++;}}

static int debug;

static
int pnetcdf_write_2d(char   *filename,
		  		  	MPI_Offset  len,
					int x,
					int y,
					int nvars,
		  			int nsteps)
{
    int i, j, rank, nprocs, nerrs=0, err;
    //int ncid, cmode, varid[NVARS], dimid[3];
	int ncid, cmode, dimid[3];
	int *varid;
    void **buf;
    double start_t, end_t;
	double io_t, max_io_t, min_io_t;

	varid = (int *)malloc(sizeof(int)*nvars);
	buf = (void **)malloc(sizeof(void *)*nvars);

    MPI_Comm comm=MPI_COMM_WORLD;
    MPI_Offset start[3], count[3];
    MPI_Info info=MPI_INFO_NULL;

    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &nprocs);

    /* set PnetCDF I/O hints */
    MPI_Info_create(&info);
    /* disable the header extent alignments
    MPI_Info_set(info, "nc_header_align_size", "1");    size in bytes
    */
    /* disable the fixed-size variable alignments */
    MPI_Info_set(info, "nc_var_align_size", "1");
	    
	/* initialize I/O buffer */
    for (i=0; i<nvars; i++) 
	{
		double *dbl_b = (double*) malloc(len * len * sizeof(double));
        for (j=0; j<len*len; j++) dbl_b[j] = rank;
        buf[i] = (void*)dbl_b;
	}
	MPI_Barrier(comm);

	
    /* create a new file for writing -----------------------------------------*/
    cmode = NC_CLOBBER | NC_64BIT_DATA;
    err = ncmpi_create(comm, filename, cmode, info, &ncid); ERR(err)
    MPI_Info_free(&info);

	int x_dim, y_dim, s_dim;
	
	err = ncmpi_def_dim(ncid, "Step", NC_UNLIMITED, &s_dim); ERR(err)
	err = ncmpi_def_dim(ncid, "X", len*x, &x_dim); ERR(err)
	err = ncmpi_def_dim(ncid, "Y", len*y, &y_dim); ERR(err)
	

	dimid[0] = s_dim;
	dimid[1] = x_dim;
	dimid[2] = y_dim;
	
	/* define variables */
	for (i=0; i<nvars; i++)
	{	
		char var_name[32];
		sprintf(var_name,"var_%d", i);
        err = ncmpi_def_var(ncid, var_name, NC_DOUBLE, 3, dimid, &varid[i]);
        ERR(err)
	}
	

    err = ncmpi_enddef(ncid); ERR(err)

	int cur_step;
	for (cur_step = 0; cur_step < nsteps; cur_step++)
	{
		start_t = MPI_Wtime();
		for (i=0; i<nvars; i++) 
		{
			double *dbl_b = (double*) buf[i];
            start[0] = cur_step;
            start[1] = len * (rank % x);
			start[2] = len * (rank / x % y);
            count[0] = 1;
            count[1] = len;
			count[2] = len;
            err = ncmpi_put_vara_double_all(ncid, varid[i], start, count, dbl_b);
            ERR(err)
            if (debug) printf("*-block %d: start=%lld %lld %lld count=%lld %lld %lld\n",i,start[0],start[1],start[2],count[0],count[1],count[2]);
		}
		end_t = MPI_Wtime();
		io_t = end_t-start_t;
		MPI_Allreduce(&io_t, &max_io_t, 1, MPI_DOUBLE, MPI_MAX, comm);
		MPI_Allreduce(&io_t, &min_io_t, 1, MPI_DOUBLE, MPI_MIN, comm);
		if (rank == 0) 
		{
			printf("%f, %f\n", max_io_t, min_io_t);
		}
	}

	err = ncmpi_close(ncid); ERR(err)

	for (i=0; i<nvars; i++) free(buf[i]);

	free(buf);
	free(varid);

	return nerrs;
}

static
int pnetcdf_read_2d(char *filename,
					int x,
					int y)
{
	int ncid;
	int rank, nprocs;
	int nerrs=0, err;
	int ndims, nvars, unlimdimid;
	char name[NC_MAX_NAME];

    double start_t, end_t;
	double io_t, max_io_t, min_io_t;

	MPI_Comm comm=MPI_COMM_WORLD;
    MPI_Info info=MPI_INFO_NULL;
	MPI_Offset *shape, *start, *count;

    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &nprocs);


	err = ncmpi_open(comm, filename, NC_NOWRITE, info, &ncid); ERR(err)
	err = ncmpi_inq_ndims(ncid, &ndims); ERR(err)
	if (ndims != 3)
	{
		printf("it is supposed to be 1(step)+2(x, y) dimensions!\n");
		nerrs++;
		return nerrs;
	}
	err = ncmpi_inq_nvars(ncid, &nvars); ERR(err)
	err = ncmpi_inq_unlimdim(ncid, &unlimdimid); ERR(err)
	if (unlimdimid != 0)
	{	
		printf("unlimited dimension id must be 0!\n");
		nerrs++;
		return nerrs;		
	}
	if (rank == 0)
		printf("# of dims: %d, # of vars: %d, unlim dim id: %d\n", ndims, nvars, unlimdimid);
	
	/* Inquire dimension */
    //dimids = (int*) malloc(ndims * sizeof(int));
	int total_steps, shape_x, shape_y;
	int len_x, len_y;
	shape = (MPI_Offset*) malloc(ndims * sizeof(MPI_Offset));
	for (int i = 0; i < ndims; i++)
	{
		err = ncmpi_inq_dim(ncid, i, name, shape+i); ERR(err)
	}
	total_steps = shape[0];
	shape_x = shape[1];
	len_x = shape_x/x;
	shape_y = shape[2];
	len_y = shape_y/y;

	// if (rank == 0)
	// {
	// 	printf("shape: %lld, %lld, %lld\n", shape[0], shape[1], shape[2]);
	// 	printf("len_x: %d, len_y: %d\n", len_x, len_y);
	// }
		

	for (int s = 0; s < total_steps; s++)
	{
		start = (MPI_Offset*) malloc(ndims * sizeof(MPI_Offset));
		count = (MPI_Offset*) malloc(ndims * sizeof(MPI_Offset));
		
		MPI_Offset varsize = 1;
		int dimpos = 0;
		start_t = MPI_Wtime();

		start[0] = s;
		start[1] = len_x * (rank % x);
		start[2] = len_y * (rank / x % y);

		count[0] = 1;
		if (start[1]+2*len_x > shape_x)
		{
			count[1] = shape_x-start[1];
		}
		else
		{
			count[1] = len_x;
		}
		if (start[2]+2*len_y > shape_y)
		{
			count[2] = shape_y-start[2];
		}
		else
		{
			count[2] = len_y;
		}

		varsize = count[0]*count[1]*count[2];
		
		for (int i = 0; i < nvars; i++)
		{
			double *dbl_b = (double*) malloc(varsize * sizeof(double));
			// printf("var: %d, rank: %d, start: %lld %lld %lld, count: %lld %lld %lld\n", i, rank, start[0], start[1], start[2], count[0], count[1], count[2]);
			err = ncmpi_get_vara_double_all(ncid, i, start, count, dbl_b); ERR(err)
			// for (int k = 0; k < varsize; k++)
			// {
			// 	printf("rank: %d, dbl_b[%d]: %f\n", rank, k, dbl_b[k]);
			// }
			free(dbl_b);
		}
		
		end_t = MPI_Wtime();
		io_t = end_t-start_t;
		MPI_Allreduce(&io_t, &max_io_t, 1, MPI_DOUBLE, MPI_MAX, comm);
		MPI_Allreduce(&io_t, &min_io_t, 1, MPI_DOUBLE, MPI_MIN, comm);
		if (rank == 0) 
		{
			printf("%f, %f\n", max_io_t, min_io_t);
		}

		free(start);
		free(count);
	}
	free(shape);
	err = ncmpi_close(ncid); ERR(err)

	return nerrs;
}

static void
usage(char *argv0)
{
    char *help =
    "Usage: %s [-h] | [-q] [-d] [-l len] [file_name]\n"
    "       [-h] Print help\n"
    "       [-q] Quiet mode\n"
    "       [-d] Debug mode\n"
    "       [-l len]: local variable of size len x len (default 10)\n"
    "       [filename]: output netCDF file name (default ./testfile.nc)\n";
    fprintf(stderr, help, argv0);
}

/*----< main() >--------------------------------------------------------------*/
int main(int argc, char** argv) {
    extern int optind;
    char filename[256];
    int i, rank, nprocs, verbose=1, nerrs=0;
	int nvars, nsteps;
	int operation=0;
	int x, y;
	
    MPI_Offset len=0;
    MPI_Comm comm=MPI_COMM_WORLD;
    //MPI_Info w_info_used, r_info_used;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &nprocs);

    /* get command-line arguments */
    debug = 0;
    while ((i = getopt(argc, argv, "hqdrwx:y:v:s:l:")) != EOF)
        switch(i) {
            case 'q': verbose = 0;
                      break;
            case 'd': debug = 1;
                      break;
            case 'l': len = atoi(optarg);
                      break;
			case 'r': operation = 0;
					  break;
			case 'w': operation = 1;
					  break;
			case 'x': x = atoi(optarg);
					  break;
			case 'y': y = atoi(optarg);
					  break;					  
			case 'v': nvars = atoi(optarg);
					  break;
			case 's': nsteps = atoi(optarg);
					  break;
            case 'h':
            default:  if (rank==0) usage(argv[0]);
                      MPI_Finalize();
                      return 1;
        }
	if (x*y != nprocs)
	{
		printf("x * y must equal to # of processes!\n");
		return 1;
	}
		
    if (argv[optind] == NULL) strcpy(filename, "testfile.nc");
    else                      snprintf(filename, 256, "%s", argv[optind]);

    len = (len <= 0) ? 10 : len;

	//nerrs += pnetcdf_write(filename, len, &w_size, &w_info_used, STEPS);
	if (operation)
	{
		nerrs += pnetcdf_write_2d(filename, len, x, y, nvars, nsteps);
	}
	else
	{
		nerrs += pnetcdf_read_2d(filename, x, y);
	}
	

	//MPI_Info_free(&w_info_used);
    //MPI_Info_free(&r_info_used);

    MPI_Finalize();
    return (nerrs > 0);

}
```

**Comment by khuck** [comment]
and the run script is:

```bash
#!/bin/bash
#BSUB -P XXXXXX
#BSUB -W 01:00
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -J pnetcdf-test
#BSUB -nnodes 20
#BSUB -alloc_flags "smt1"

echo $LSB_DJOB_NUMPROC
TOTAL_NODES=$(((LSB_DJOB_NUMPROC-1)/42))
echo $TOTAL_NODES
WR_PROC_PER_NODE=20
    
WR_PROC=$((TOTAL_NODES*WR_PROC_PER_NODE))
echo $WR_PROC

VARS=500
STEPS=100

jsrun -n $WR_PROC -a 1 -c 1 -r $WR_PROC_PER_NODE ./pnetcdf_test_block -l 10 -w -x 20 -y 20 -v $VARS -s $STEPS testfile.nc > wr_${WR_PROC}proc_${VARS}vars_${STEPS}steps


```

**Comment by wkliao** [comment]
Thanks. From the profiling results, I am seeing 23.14 seconds spent on `MPI_Allreduce`, which is an aggregated cost inside of calls to `ncmpi_put_vara_double_all`. I am puzzling why it has such a high cost, compared to 22.798 seconds spent on `MPI_File_write_at_all`. In  PnetCDF, `MPI_Allreduce` is called only when updating the number of records, an 8-byte integer, to the header. I am looking into PnetCDF source codes and hope to better understand this behavior.

**Comment by khuck** [comment]
Keep in mind this is a mean profile - the behavior is quite different between ranks.  For all ranks except 0, the time is spent in MPI_Allreduce.  See the attached figure (if it comes through on the web site...) comparing the mean performance across 400 ranks to rank 0, looking at inclusive times:

http://www.nic.uoregon.edu/~khuck/pnetcdf.png


> On Oct 3, 2019, at 1:44 PM, Wei-keng Liao <notifications@github.com> wrote:
> 
> Thanks. From the profiling results, I am seeing 23.14 seconds spent on MPI_Allreduce, which is an aggregated cost inside of calls to ncmpi_put_vara_double_all. I am puzzling why it has such a high cost, compared to 22.798 seconds spent on MPI_File_write_at_all. In PnetCDF, MPI_Allreduce is called only when updating the number of records, an 8-byte integer, to the header. I am looking into PnetCDF source codes and hope to better understand this behavior.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Kevin Huck, PhD
Research Associate / Computer Scientist
OACISS - Oregon Advanced Computing Institute for Science and Society
University of Oregon
khuck@cs.uoregon.edu
http://tau.uoregon.edu

**Comment by wkliao** [comment]
Hi @khuck 
Thanks for the additional chart. I checked the benchmark program and the parameters
used in your run. The high cost on MPI_Allreduce can be explained by the small-size
variables used in the run. Below are the parameters and I/O operations.
The number of MPI processes is 400 and together they write 500 variables collectively, one
at a time. Each variable is of size 320000B=0.31 MiB. The benchmark repeats this for 100
time steps. This I/O pattern will produce 50,000 MPI_File_write_at_all and 50,000 MPI_Allreduce
made by PnetCDF. ROMIO internally also calls MPI_Allreduce inside of MPI_File_write_at_all.
Thus, the observed high cost for MPI_Allreduce reported by TAU is reasonable.

Usually I/O benchmarks use a much larger variable size. In that case, the cost of
MPI_Allreduce will take less percentage of the total time. Are you using the above
same I/O pattern to benchmark ADIOS and HDF5, as shown in the wiki page?

**Comment by khuck** [comment]
@wkliao I only ran the experiments for Lipeng Wan at ORNL, I'll forward your email to him and he can chime in if necessary - he wrote the benchmark.

**Comment by khuck** [comment]
@wkliao Lipeng says: "Yes. The same I/O pattern is used to benchmark all three I/O libraries." - so I guess this benchmark was intended to stress this particular feature.

**Comment by wkliao** [comment]
Since this pattern is unusual, maybe you can consider adding the description of I/O pattern in the wiki page. There are I/O benchmarks more commonly used by I/O community.  Please see https://www.mcs.anl.gov/~thakur/pio-benchmarks.html

**Comment by roblatham00** [comment]
This kind of workload is a good reminder of the benefits of pnetcdf's non-blocking interface.   

 The independent operations are a fine choice for when all the clients are on one node (`#BSUB -nnodes 1`): gpfs client caching should help a lot here.   I am less sure how well Summit I/O fares when multiple nodes are involved -- independent I/O will win on "less MPI synchronization" but lose out on "file system cache invalidation overhead".  

In the end, like Wei-keng says pnetcdf performance is adequate given the workload and topology.  

We can discuss further if single-node I/O is the dominant I/O workload on Summit or not...
