### ISSUE TITLE
Bash-specific shell script comparison in `taucc` and `taucxx` make for noisy compilation (Ubuntu)

### ISSUE THREAD

**Issue by ken-lauer** [UO-OACISS/tau2#17]
These comparisons, while valid for `bash`, result in syntax errors with `/bin/sh` on modern Ubuntu-based systems:
https://github.com/UO-OACISS/tau2/blob/985aaed797ee0195521af523409378b0d49e7267/tools/src/taucc#L68
and
https://github.com/UO-OACISS/tau2/blob/985aaed797ee0195521af523409378b0d49e7267/tools/src/taucxx#L68

```
$ taucc --help
$TAU_ROOT/x86_64/bin/taucc: 68: [: 1: unexpected operator
Usage: tau_compiler.sh
  -optVerbose                   Turn on verbose debugging message
...
```

The Dash shell apparently replaced `bash` as the default for `/bin/sh` back in Ubuntu 6.1 - https://wiki.ubuntu.com/DashAsBinSh

A quick fix is just to switch it up to the correct numerical comparison form:

```bash
if [ $# -eq 0 ]; then
```

(I'd submit the change, but it doesn't look like the primary development happens on this mirror...)

**Comment by wspear** [comment]
Thanks for the report. I applied your suggested change to taucc, tauf90 and taucxx. It should be reflected in the github repo by tomorrow.
