### ISSUE TITLE
support new cray compiler names

### ISSUE THREAD

**Issue by lukebroskop** [UO-OACISS/tau2#7]
Hi,
By default spack is trying to set crayCC, craycc, crayftn as tau build options for c++, cc, and fortran. crayCC, craycc, crayftn are "wrapper-less" approaches to using CCE. Is it possible to add crayCC, craycc, crayftn to configure script?

Thanks!
Luke

**Comment by khuck** [comment]
Possible? yes - in the configure script, there are places where it checks if the OS is craycnl, and if so, assumes cc, CC and ftn are the compilers. Just look for those places...

**Comment by lukebroskop** [comment]
Oh, I'll create a PR. Thanks!

**Comment by wspear** [comment]
Note that this PR should fix the TAU package: https://github.com/spack/spack/pull/34175 However there are still advantages to supporting the direct cray compilers.

**Comment by lukebroskop** [comment]
Thanks @wspear, I had done a different fix to the package. But your fix is better!
